### PR TITLE
BSR refactoring test of challenge-item

### PR DESCRIPTION
**Pull request by bdavidxyz**
This closes https://github.com/sgmap/pix-live/issues/147

It should also prepare refactoring of big challenge-item.js

### CODE REVIEW

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://bsr-test-displayed-errors-in-front.pix.beta.gouv.fr. Please check it out

**Comment by jbuget** [comment]
Il y a des espaces et des lignes (ainsi qu'à mon goût des instructions `else`) en trop mais sinon c'est du super boulot. Bravo et merci ! ;-)

**Pull request merged**
