### PR TITLE
US4 demarrer epreuve

### PR DESCRIPTION
**Pull request by mackwic**
With mocha and chai testing \ò/

Work:
- [x] make the test suite works with mocha
- [x] uniformize the existing pix-live with User Stories
- [x] validate the acceptance criteria of the US
- [x] ~~🐛 why my acceptance test is not ran ?~~ (fixed)

### CODE REVIEW

**Comment by mackwic** [comment]
Today will be a day remembered as “the Great Battle against `import ... from`”. Daughters and sons will learn generations to generations how the malicious `ember-cli` used tricks to confuse the good and honest and mighty Developer whom cannot load any third-party libraries. They will learn how the good and honest and mighty Developer conquered the `ember-cli` in a glorious final.

PRAISE THE SUN 🌞 \o/

**Comment by MattiSG** [comment]
capture d ecran 2016-08-02 a 18 59 11  😂 

Unfortunately, they won't be able to learn anything, because the commit message wasn't [great](http://chris.beams.io/posts/git-commit/)  :wink:

**Comment by mackwic** [comment]
> because the commit message wasn't great 😉

Be reassured, sometimes I make good commit messages. 😄 Don't take my words for it, check [in my](https://github.com/mackwic/rspec/commits/master) [other](https://github.com/mackwic/dhcpq/commits/master) [OSS work](https://github.com/mackwic/colored/commits/master).

The issue here was ember documentation and messed-up dependencies. This is me, learning ember. No more.

And yeah, build is broken. Next commit will fix it. Tomorrow. One battle a day, one fight at a time.

**Comment by mackwic** [comment]
CI error was only a question of old phantomJS. Updated the image to Ubuntu 14.04 👍

**Pull request merged**
