### PR TITLE
Tech use branch api on ember

### PR DESCRIPTION
**Pull request by mackwic**

### CODE REVIEW

**Comment by twickham** [comment]
I've deployed this PR to http://tech-use-branch-api-on-ember.pix.beta.gouv.fr. Please check it out

**Comment by mackwic** [comment]
En local c'est bon

screen shot 2016-10-07 at 16 37 14

**Comment by twickham** [comment]
I've deployed this PR to http://tech-use-branch-api-on-ember.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://tech-use-branch-api-on-ember.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://tech-use-branch-api-on-ember.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://tech-use-branch-api-on-ember.pix.beta.gouv.fr. Please check it out

**Comment by mackwic** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by twickham** [comment]
I've deployed this PR to http://tech-use-branch-api-on-ember.pix.beta.gouv.fr. Please check it out

**Pull request merged**
