### PR TITLE
little refacto for challengeItem

### PR DESCRIPTION
**Pull request by mackwic**

### CODE REVIEW

**Comment by twickham** [comment]
I've deployed this PR to http://refacto-challenge-item.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://refacto-challenge-item.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://refacto-challenge-item.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://refacto-challenge-item.pix.beta.gouv.fr. Please check it out

**Comment by mackwic** [comment]
It's blocking for my user story. I merge it, sorry :/

**Pull request merged**
