### PR TITLE
[#502] [FEATURE] Intégrer la nouvelle règle de calcul des pix au scoring (US-671 & US-672 & US-482).

### PR DESCRIPTION
**Pull request by jilljenn**
Ongoing work.

### CODE REVIEW

**Comment by jbuget** [comment]
I've deployed this PR to http://671-fix-scoring.pix.beta.gouv.fr. Please check it out

**Comment by jilljenn** [comment]
Bref ça me semble OK mais il y a ce petit warning qui m'inquiète (c'est embêtant parce que les promesses non rattrapées font passer les tests) :

Dans `assessment-service_test.js` :

          ✓ should detect Assessment created for preview Challenge and do not evaluate score
    (node:9723) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): undefined
    (node:9723) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
          when we retrieved the assessment
            ✓ should return a rejected promise when the repository is on error

**Comment by jbuget** [comment]
I've deployed this PR to http://671-fix-scoring.pix.beta.gouv.fr. Please check it out

**Comment by jbuget** [comment]
I've deployed this PR to http://671-fix-scoring.pix.beta.gouv.fr. Please check it out

**Comment by jilljenn** [comment]
J'attends vos reviews avant de merge dev ;) Enfin c'est vrai que je pourrais rebase dev et merge -f.

**Comment by jbuget** [comment]
I've deployed this PR to http://671-fix-scoring.pix.beta.gouv.fr. Please check it out

**Pull request merged**
