### PR TITLE
BSR : Clean controllers

### PR DESCRIPTION
**Pull request by bdavidxyz**
Basically, each controller should be empty. This is a first attempt on app/controllers/assessments/get-challenge.js

### CODE REVIEW

**Comment by twickham** [comment]
I've deployed this PR to http://clean-controllers.pix.beta.gouv.fr. Please check it out

**Comment by jbuget** [comment]
Et du coup, vu que les controllers sont vides, on peut les supprimer ?
si oui => delete_with_pride_and_smile()

**Comment by twickham** [comment]
I've deployed this PR to http://clean-controllers.pix.beta.gouv.fr. Please check it out

**Comment by twickham** [comment]
I've deployed this PR to http://clean-controllers.pix.beta.gouv.fr. Please check it out

**Pull request merged**
