### PR TITLE
[#318][FEATURE] rendre désactivable les pre-traitements des réponses/solutions

### PR DESCRIPTION
**Pull request by bdavidxyz**

### CODE REVIEW

**Comment by jbuget** [comment]
I've deployed this PR to http://330-deactivate-pretreatments.pix.beta.gouv.fr. Please check it out

**Comment by jbuget** [comment]
I've deployed this PR to http://330-deactivate-pretreatments.pix.beta.gouv.fr. Please check it out

**Comment by jbuget** [comment]
I've deployed this PR to http://330-deactivate-pretreatments.pix.beta.gouv.fr. Please check it out

**Comment by jbuget** [comment]
I've deployed this PR to http://330-deactivate-pretreatments.pix.beta.gouv.fr. Please check it out

**Comment by bdavidxyz** [comment]
remplacée suite au merge

**Pull request closed without merging**
